services:
  stock-save:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-save
    ports:
      - "8810:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./log:/app/log
      - ./.env:/app/.env:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
