[supervisord]
nodaemon=true
user=root
logfile=/app/log/supervisord.log
pidfile=/tmp/supervisord.pid

[program:cron]
command=crond -f
autostart=true
autorestart=true
stdout_logfile=/app/log/cron.log
stderr_logfile=/app/log/cron.log

[program:web]
command=uv run web
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/log/web.log
stderr_logfile=/app/log/web.log
