### 腾讯混元 hunyuan-lite 模型
# @name hunyuanLiteChat
POST https://api.hunyuan.cloud.tencent.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv HUNYUAN_API_KEY}}

{
  "model": "hunyuan-lite",
  "messages": [
    {
      "role": "system",
      "content": "你是一位北京现代汽车品牌的专家，对车型配置非常熟悉。\n以下是一道单选题，请只从题目实际列出的选项里选择正确答案。\n注意：题目可能只给出 2 个或 3 个选项，并非永远 4 个。\n请仅输出对应选项的那个英文字母，不要输出任何其他字符。"
    },
    {
      "role": "user",
      "content": "Q：第五代 胜达的环抱式“H”型LED氛围灯有多种颜色可选？\nC. 32色\nD. 64色"
    }
  ]
}

# 正确答案 C
# Q：第五代 胜达的外观设计语言是？\nA. 光影式造型\nB. 中国专属方盒子造型\nC. 全球 One Model 方盒子造型\nD. 大方盒子造型

# 正确答案 A
# Q: 第五代 胜达尾门最大开启角度为？\nA. A、90.4°\nB. B、94.0°\nC. C、100.4°\nD. D、140.0°

# 正确答案 D
# Q：第五代 胜达的环抱式“H”型LED氛围灯有多种颜色可选？\nC. 32色\nD. 64色

# response
# {
#   "id": "af72424f0eebd36f362298a1df72c34b",
#   "object": "chat.completion",
#   "created": 1761552936,
#   "model": "hunyuan-lite",
#   "system_fingerprint": "",
#   "choices": [
#     {
#       "index": 0,
#       "message": {
#         "role": "assistant",
#         "content": "C"
#       },
#       "finish_reason": "stop"
#     }
#   ],
#   "usage": {
#     "prompt_tokens": 109,
#     "completion_tokens": 2,
#     "total_tokens": 111
#   },
#   "note": "以上内容为AI生成，不代表开发者立场，请勿删除或修改本标记"
# }
