### 获取用户信息
# @name getUserInfo
GET {{$dotenv BASE_URL}}/v1/app/account/users/info HTTP/1.1
Content-Type: application/json
token: {{$dotenv BJXD}}
device: mp

# response
# {
#   "code": 0,
#   "data": {
#     "hid": "a6688ec1a9ee429fa7b68d50e0c92b1f",
#     "created_at": "2024-11-27 17:42:20",
#     "updated_at": "2024-11-27 17:42:20",
#     "nid": 10296971,
#     "name": "",
#     "nickname": "现代用户ZV4OWy",
#     "user_status_hid": "",
#     "is_forbid": 0,
#     "is_car_owner": 0,
#     "is_car_bind": 0,
#     "sex": 1,
#     "avatar": "https://bm2-res.bluemembers.com.cn/res/static/user_avatar_default.png",
#     "phone": "13041003258",
#     "email": "",
#     "location": "",
#     "signature": "",
#     "h_code": "",
#     "wx_name": "",
#     "wx_open_id": "",
#     "wx_union_id": "",
#     "wx_is_bind": 0,
#     "wx_avatar": "",
#     "qq_open_id": "",
#     "qq_union_id": "",
#     "qq_avatar": "",
#     "qq_name": "",
#     "invite_hid": "",
#     "status": 0,
#     "province": "",
#     "city": "",
#     "area": "",
#     "dss_code": "",
#     "reg_source": "mp",
#     "logoff_time": "0001-01-01 00:00:00",
#     "apple_unique_id": "",
#     "apple_name": "",
#     "apple_is_bind": 0,
#     "license_no": "",
#     "style_name": "",
#     "attention_num": 0,
#     "fans_num": 0,
#     "like_num": 0,
#     "medal_num": 0,
#     "score_value": 247,
#     "if_signed_in": true,
#     "status_name": "",
#     "status_icon": "",
#     "oa_name": "",
#     "oa_dept": "",
#     "show_carnival": false,
#     "belongs": 0,
#     "is_vip": true,
#     "level": 1,
#     "is_open_shop": false,
#     "is_open_hb": false,
#     "is_partner": false,
#     "is_show_card": false,
#     "is_vip_upgrade": false,
#     "is_expert": false,
#     "style_id": 0,
#     "medal_icon": "",
#     "wish_hid": "",
#     "order_hid": "",
#     "news_customer_care": false,
#     "news_customer_care_url": "",
#     "tag_list": [],
#     "is_have_draw_num": false,
#     "is_dealer_official": false,
#     "medal_info": {
#       "icon": "",
#       "name": "",
#       "date": "",
#       "desc": "",
#       "is_gain": 0,
#       "desc_item": null,
#       "jump_type": 0,
#       "tips": "",
#       "is_wear": 0,
#       "lv": 0,
#       "type": 0
#     }
#   },
#   "msg": "",
#   "title": ""
# }
